#!/usr/bin/bash

set -e
archive=test-archive
cmd=./target/release/dm-archive

checkout() {
	echo Checking out $1 ...

	pushd > /dev/null 2>&1
	git checkout $1 > /dev/null 2>&1
	sync -f ./README > /dev/null 2>&1
	pushd > /dev/null 2>&1
}

snapshot() {
        echo Taking snapshot ...
        lvcreate -s --name $1 test-vg/kernel-builds
        lvchange -kn test-vg/$1
        lvchange -ay test-vg/$1
        lvchange -an test-vg/$1
        lvchange -ay test-vg/$1
}

pack() {
	checkout $1
	snapshot $1

	echo Packing $1
	$cmd pack -a $archive /dev/test-vg/$1
}

pack_delta() {
	checkout $1
	snapshot $1

	echo Packing delta $2 -\> $1
	echo $cmd pack -a $archive /dev/test-vg/$1 --delta-stream `get_id $2` --delta-device $2
 	time $cmd pack -a $archive /dev/test-vg/$1 --delta-stream `get_id $2` --delta-device /dev/test-vg/$2
}

get_id() {
	$cmd list -a $archive 2>&1 | grep $1 | cut -f1 -d' '
}
 
verify() {
	echo Verifying $1
	$cmd verify -a $archive --stream `get_id $1` /dev/test-vg/$1
}

remove() {
	lvremove -y /dev/test-vg/$1
}

cycle() {
	pack $1
	verify $1
	remove $1
}

pack_deltas() {
	while (( "$#" > 1 )); do
		pack_delta $2 $1
		verify $2
		remove $1
		shift 1
	done
}

#-----------------------

echo Cleaning up from earlier run ...
rm -rf $archive
umount ./test-mnt | true
lvremove -fy test-vg/pool | true

echo Creating archive ...
$cmd create -a $archive --block-size 4096

echo Creating thin pool ...
lvcreate -L 100G --thinpool pool test-vg

echo Creating thin dev ...
lvcreate -V100G test-vg/pool -n kernel-builds

echo Running mkfs.ext4 ...
mkfs.ext4 /dev/test-vg/kernel-builds > /dev/null

echo Cloning kernel repo
mount /dev/test-vg/kernel-builds ./test-mnt
pushd test-mnt
git clone ~ejt/work/RedHat/riscv-kernel/ linux
cd linux
pushd

pack v5.0
verify v5.0
pack_deltas v5.0 v5.1 v5.2 v5.3 v5.4 v5.5 v5.6 v5.7 v5.8 v5.9 v5.10 v5.11 v5.12 v5.13

